name: build-action
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 20
    - run: npm ci
      shell: bash
    - run: npm test
      shell: bash
    - run: npm run build
      shell: bash
